from .env import env

BROKER_URL = env.str('BROKER_URL')
CELERY_ACCEPT_CONTENT = env.list('CELERY_ACCEPT_CONTENT')
CELERY_TASK_SERIALIZER = env.str('CELERY_TASK_SERIALIZER')
CELERY_RESULT_SERIALIZER = env.str('CELERY_RESULT_SERIALIZER')
CELERY_RESULT_BACKEND = env.str('CELERY_RESULT_BACKEND')
