# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Maximum 50 characters', max_length=200, unique=True),
        ),
    ]
