# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='audios.Tag'),
        ),
    ]
