# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:47
from __future__ import unicode_literals

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import imagekit.models.fields
import muzicbox.utils.models_helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mbid', models.CharField(blank=True, max_length=50, null=True)),
                ('playcount', models.PositiveIntegerField(blank=True, default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Suggested value automatically generated from name. Must be unique.', populate_from='name', unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=muzicbox.utils.models_helpers.UploadToPathAndRename('artists'))),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
