version: 2
jobs:
  build:
    working_directory: ~/reactmusic
    docker:
      - image: circleci/python:3.6
        environment:
          DEBUG: False
          STATIC_ROOT: ~/reactmusic/static
          ALLOWED_HOSTS: reactmusic.net
          DATABASE_URL: psql://root@localhost/reactmusic_test?sslmode=disable
          CACHE_URL: rediscache://127.0.0.1:6379:1?client_class=django_redis.client.DefaultClient
          MEDIA_ROOT: ~/reactmusic/media
          BROKER_URL: redis://localhost:6379/1
          CELERY_ACCEPT_CONTENT: json
          CELERY_TASK_SERIALIZER: json
          CELERY_RESULT_SERIALIZER: json
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
      - image: redis:3.2-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/circle.txt" }}
      - run:
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements/circle.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/circle.txt" }}
          paths:
            - "env"
      - run:
          command: |
            source env/bin/activate
            python manage.py test
      # - run:
      #     command: |
      #       source env/bin/activate
      #       pylama
