export default {
  songs: {
    count: null,
    next: null,
    previous: null,
    results: [],
  },
  playlist: {
    count: null,
    next: null,
    previous: null,
    results: [],
  },
  play_next_list: [],
  searchSongValue: "",
  search_artist_value: "",
  artists: {
    count: null,
    next: null,
    previous: null,
    results: [],
  },
  no_songs: false,
  filterTagValue: null,
  orderingType: null,
  active_song: {
    id: "",
    name: "",
    length: 0,
    has_lyrics: false,
    slug: "",
    audio_file: "",
    bitrate: null,
    tags: [],
    playcount: 0,
    artist: { id: "", name: "", slug: "" },
    small_image_thumbnail: "",
    extra_sm_image_thumbnail: "",
  },
  progress: 0,
  isPlaying: false,
  isLoading: false,
  is_repeat: false,
  is_menu_open: false,
  isAuthorSearch: false,
  is_search_song_loading: false,
  is_search_artist_loading: false,
  scroll_to_song: null,
};
