# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:47
from __future__ import unicode_literals

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import reactmusic.utils.models_helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('mbid', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Suggested value automatically generated from name. Must be unique.', populate_from='name', unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=reactmusic.utils.models_helpers.UploadToPathAndRename('albums'))),
                ('artist', models.ForeignKey(blank=True, help_text='artist or band', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.Artist')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('mbid', models.CharField(blank=True, max_length=50, null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('playcount', models.PositiveIntegerField(blank=True, default=0)),
                ('is_presentation', models.BooleanField(default=False, help_text='defines if audio will be shown for presentational purposes')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=reactmusic.utils.models_helpers.UploadToPathAndRename('covers'))),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Suggested value automatically generated from name. Must be unique.', populate_from='name', unique=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('lyrics', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, help_text='musical album', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='audios.Album')),
                ('artist', models.ForeignKey(blank=True, help_text='artist or band', on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='artists.Artist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Maximum 50 characters', max_length=50, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Suggested value automatically generated from name. Must be unique.', populate_from='name', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Tick to make this entry live (see also the publication date). Note that administrators (like yourself) are allowed to preview inactive entries whereas the general public aren't.")),
                ('short_description', models.CharField(blank=True, help_text='Maximum 250 characters', max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='audios.Tag'),
        ),
    ]
