export default {
  songs: {
    count: null,
    next: null,
    previous: null,
    results: [],
  },
  playlist: {
    count: null,
    next: null,
    previous: null,
    results: [],
  },
  play_next_list: [],
  search_song_value: "",
  search_artist_value: "",
  artists: {
    count: null,
    next: null,
    previous: null,
    results: [],
  },
  no_songs: false,
  filter_tag_value: null,
  ordering_type: null,
  song: {
    id: "",
    name: "",
    lyrics: "",
    audio_file: "",
    artist: { name: "" },
    large_image_thumbnail: "",
    extra_sm_image_thumbnail: "",
  },
  is_playing: false,
  is_loading: true,
  is_menu_open: false,
  is_author_search: false,
  is_search_song_loading: false,
  is_search_artist_loading: false,
  scroll_to_song: null,
};
